import React, { Suspense, lazy } from 'react';

const AD = lazy(() => import('./countries/Ad'));
const AE = lazy(() => import('./countries/Ae'));
const AF = lazy(() => import('./countries/Af'));
const AG = lazy(() => import('./countries/Ag'));
const AI = lazy(() => import('./countries/Ai'));
const AL = lazy(() => import('./countries/Al'));
const AM = lazy(() => import('./countries/Am'));
const AO = lazy(() => import('./countries/Ao'));
const AQ = lazy(() => import('./countries/Aq'));
const AR = lazy(() => import('./countries/Ar'));
const AS = lazy(() => import('./countries/As'));
const AT = lazy(() => import('./countries/At'));
const AU = lazy(() => import('./countries/Au'));
const AW = lazy(() => import('./countries/Aw'));
const AX = lazy(() => import('./countries/Ax'));
const AZ = lazy(() => import('./countries/Az'));
const BA = lazy(() => import('./countries/Ba'));
const BB = lazy(() => import('./countries/Bb'));
const BD = lazy(() => import('./countries/Bd'));
const BE = lazy(() => import('./countries/Be'));
const BF = lazy(() => import('./countries/Bf'));
const BG = lazy(() => import('./countries/Bg'));
const BH = lazy(() => import('./countries/Bh'));
const BI = lazy(() => import('./countries/Bi'));
const BJ = lazy(() => import('./countries/Bj'));
const BL = lazy(() => import('./countries/Bl'));
const BM = lazy(() => import('./countries/Bm'));
const BN = lazy(() => import('./countries/Bn'));
const BO = lazy(() => import('./countries/Bo'));
const BQ = lazy(() => import('./countries/Bq'));
const BR = lazy(() => import('./countries/Br'));
const BS = lazy(() => import('./countries/Bs'));
const BT = lazy(() => import('./countries/Bt'));
const BV = lazy(() => import('./countries/Bv'));
const BW = lazy(() => import('./countries/Bw'));
const BY = lazy(() => import('./countries/By'));
const BZ = lazy(() => import('./countries/Bz'));
const CA = lazy(() => import('./countries/Ca'));
const CC = lazy(() => import('./countries/Cc'));
const CD = lazy(() => import('./countries/Cd'));
const CF = lazy(() => import('./countries/Cf'));
const CG = lazy(() => import('./countries/Cg'));
const CH = lazy(() => import('./countries/Ch'));
const CI = lazy(() => import('./countries/Ci'));
const CK = lazy(() => import('./countries/Ck'));
const CL = lazy(() => import('./countries/Cl'));
const CM = lazy(() => import('./countries/Cm'));
const CN = lazy(() => import('./countries/Cn'));
const CO = lazy(() => import('./countries/Co'));
const CR = lazy(() => import('./countries/Cr'));
const CU = lazy(() => import('./countries/Cu'));
const CV = lazy(() => import('./countries/Cv'));
const CW = lazy(() => import('./countries/Cw'));
const CX = lazy(() => import('./countries/Cx'));
const CY = lazy(() => import('./countries/Cy'));
const CZ = lazy(() => import('./countries/Cz'));
const DE = lazy(() => import('./countries/De'));
const DJ = lazy(() => import('./countries/Dj'));
const DK = lazy(() => import('./countries/Dk'));
const DM = lazy(() => import('./countries/Dm'));
const DO = lazy(() => import('./countries/Do'));
const DZ = lazy(() => import('./countries/Dz'));
const EC = lazy(() => import('./countries/Ec'));
const EE = lazy(() => import('./countries/Ee'));
const EG = lazy(() => import('./countries/Eg'));
const EH = lazy(() => import('./countries/Eh'));
const ER = lazy(() => import('./countries/Er'));
const ES = lazy(() => import('./countries/Es'));
const ET = lazy(() => import('./countries/Et'));
const EU = lazy(() => import('./countries/Eu'));
const FI = lazy(() => import('./countries/Fi'));
const FJ = lazy(() => import('./countries/Fj'));
const FK = lazy(() => import('./countries/Fk'));
const FM = lazy(() => import('./countries/Fm'));
const FO = lazy(() => import('./countries/Fo'));
const FR = lazy(() => import('./countries/Fr'));
const GA = lazy(() => import('./countries/Ga'));
const GB = lazy(() => import('./countries/Gb'));
const ENG = lazy(() => import('./countries/GbEng'));
const NIR = lazy(() => import('./countries/GbNir'));
const SCT = lazy(() => import('./countries/GbSct'));
const WLS = lazy(() => import('./countries/GbWls'));
const GD = lazy(() => import('./countries/Gd'));
const GE = lazy(() => import('./countries/Ge'));
const GF = lazy(() => import('./countries/Gf'));
const GG = lazy(() => import('./countries/Gg'));
const GH = lazy(() => import('./countries/Gh'));
const GI = lazy(() => import('./countries/Gi'));
const GL = lazy(() => import('./countries/Gl'));
const GM = lazy(() => import('./countries/Gm'));
const GN = lazy(() => import('./countries/Gn'));
const GP = lazy(() => import('./countries/Gp'));
const GQ = lazy(() => import('./countries/Gq'));
const GR = lazy(() => import('./countries/Gr'));
const GS = lazy(() => import('./countries/Gs'));
const GT = lazy(() => import('./countries/Gt'));
const GU = lazy(() => import('./countries/Gu'));
const GW = lazy(() => import('./countries/Gw'));
const GY = lazy(() => import('./countries/Gy'));
const HK = lazy(() => import('./countries/Hk'));
const HM = lazy(() => import('./countries/Hm'));
const HN = lazy(() => import('./countries/Hn'));
const HR = lazy(() => import('./countries/Hr'));
const HT = lazy(() => import('./countries/Ht'));
const HU = lazy(() => import('./countries/Hu'));
const ID = lazy(() => import('./countries/Id'));
const IE = lazy(() => import('./countries/Ie'));
const IL = lazy(() => import('./countries/Il'));
const IM = lazy(() => import('./countries/Im'));
const IN = lazy(() => import('./countries/In'));
const IO = lazy(() => import('./countries/Io'));
const IQ = lazy(() => import('./countries/Iq'));
const IR = lazy(() => import('./countries/Ir'));
const IS = lazy(() => import('./countries/Is'));
const IT = lazy(() => import('./countries/It'));
const JE = lazy(() => import('./countries/Je'));
const JM = lazy(() => import('./countries/Jm'));
const JO = lazy(() => import('./countries/Jo'));
const JP = lazy(() => import('./countries/Jp'));
const KE = lazy(() => import('./countries/Ke'));
const KG = lazy(() => import('./countries/Kg'));
const KH = lazy(() => import('./countries/Kh'));
const KI = lazy(() => import('./countries/Ki'));
const KM = lazy(() => import('./countries/Km'));
const KN = lazy(() => import('./countries/Kn'));
const KP = lazy(() => import('./countries/Kp'));
const KR = lazy(() => import('./countries/Kr'));
const KW = lazy(() => import('./countries/Kw'));
const KY = lazy(() => import('./countries/Ky'));
const KZ = lazy(() => import('./countries/Kz'));
const LA = lazy(() => import('./countries/La'));
const LB = lazy(() => import('./countries/Lb'));
const LC = lazy(() => import('./countries/Lc'));
const LI = lazy(() => import('./countries/Li'));
const LK = lazy(() => import('./countries/Lk'));
const LR = lazy(() => import('./countries/Lr'));
const LS = lazy(() => import('./countries/Ls'));
const LT = lazy(() => import('./countries/Lt'));
const LU = lazy(() => import('./countries/Lu'));
const LV = lazy(() => import('./countries/Lv'));
const LY = lazy(() => import('./countries/Ly'));
const MA = lazy(() => import('./countries/Ma'));
const MC = lazy(() => import('./countries/Mc'));
const MD = lazy(() => import('./countries/Md'));
const ME = lazy(() => import('./countries/Me'));
const MF = lazy(() => import('./countries/Mf'));
const MG = lazy(() => import('./countries/Mg'));
const MH = lazy(() => import('./countries/Mh'));
const MK = lazy(() => import('./countries/Mk'));
const ML = lazy(() => import('./countries/Ml'));
const MM = lazy(() => import('./countries/Mm'));
const MN = lazy(() => import('./countries/Mn'));
const MO = lazy(() => import('./countries/Mo'));
const MP = lazy(() => import('./countries/Mp'));
const MQ = lazy(() => import('./countries/Mq'));
const MR = lazy(() => import('./countries/Mr'));
const MS = lazy(() => import('./countries/Ms'));
const MT = lazy(() => import('./countries/Mt'));
const MU = lazy(() => import('./countries/Mu'));
const MV = lazy(() => import('./countries/Mv'));
const MW = lazy(() => import('./countries/Mw'));
const MX = lazy(() => import('./countries/Mx'));
const MY = lazy(() => import('./countries/My'));
const MZ = lazy(() => import('./countries/Mz'));
const NA = lazy(() => import('./countries/Na'));
const NC = lazy(() => import('./countries/Nc'));
const NE = lazy(() => import('./countries/Ne'));
const NF = lazy(() => import('./countries/Nf'));
const NG = lazy(() => import('./countries/Ng'));
const NI = lazy(() => import('./countries/Ni'));
const NL = lazy(() => import('./countries/Nl'));
const NO = lazy(() => import('./countries/No'));
const NP = lazy(() => import('./countries/Np'));
const NR = lazy(() => import('./countries/Nr'));
const NU = lazy(() => import('./countries/Nu'));
const NZ = lazy(() => import('./countries/Nz'));
const OM = lazy(() => import('./countries/Om'));
const PA = lazy(() => import('./countries/Pa'));
const PE = lazy(() => import('./countries/Pe'));
const PF = lazy(() => import('./countries/Pf'));
const PG = lazy(() => import('./countries/Pg'));
const PH = lazy(() => import('./countries/Ph'));
const PK = lazy(() => import('./countries/Pk'));
const PL = lazy(() => import('./countries/Pl'));
const PM = lazy(() => import('./countries/Pm'));
const PN = lazy(() => import('./countries/Pn'));
const PR = lazy(() => import('./countries/Pr'));
const PS = lazy(() => import('./countries/Ps'));
const PT = lazy(() => import('./countries/Pt'));
const PW = lazy(() => import('./countries/Pw'));
const PY = lazy(() => import('./countries/Py'));
const QA = lazy(() => import('./countries/Qa'));
const RE = lazy(() => import('./countries/Re'));
const RO = lazy(() => import('./countries/Ro'));
const RS = lazy(() => import('./countries/Rs'));
const RU = lazy(() => import('./countries/Ru'));
const RW = lazy(() => import('./countries/Rw'));
const SA = lazy(() => import('./countries/Sa'));
const SB = lazy(() => import('./countries/Sb'));
const SC = lazy(() => import('./countries/Sc'));
const SD = lazy(() => import('./countries/Sd'));
const SE = lazy(() => import('./countries/Se'));
const SG = lazy(() => import('./countries/Sg'));
const SH = lazy(() => import('./countries/Sh'));
const SI = lazy(() => import('./countries/Si'));
const SJ = lazy(() => import('./countries/Sj'));
const SK = lazy(() => import('./countries/Sk'));
const SL = lazy(() => import('./countries/Sl'));
const SM = lazy(() => import('./countries/Sm'));
const SN = lazy(() => import('./countries/Sn'));
const SO = lazy(() => import('./countries/So'));
const SR = lazy(() => import('./countries/Sr'));
const SS = lazy(() => import('./countries/Ss'));
const ST = lazy(() => import('./countries/St'));
const SV = lazy(() => import('./countries/Sv'));
const SX = lazy(() => import('./countries/Sx'));
const SY = lazy(() => import('./countries/Sy'));
const SZ = lazy(() => import('./countries/Sz'));
const TC = lazy(() => import('./countries/Tc'));
const TD = lazy(() => import('./countries/Td'));
const TF = lazy(() => import('./countries/Tf'));
const TG = lazy(() => import('./countries/Tg'));
const TH = lazy(() => import('./countries/Th'));
const TJ = lazy(() => import('./countries/Tj'));
const TK = lazy(() => import('./countries/Tk'));
const TL = lazy(() => import('./countries/Tl'));
const TM = lazy(() => import('./countries/Tm'));
const TN = lazy(() => import('./countries/Tn'));
const TO = lazy(() => import('./countries/To'));
const TR = lazy(() => import('./countries/Tr'));
const TT = lazy(() => import('./countries/Tt'));
const TV = lazy(() => import('./countries/Tv'));
const TW = lazy(() => import('./countries/Tw'));
const TZ = lazy(() => import('./countries/Tz'));
const UA = lazy(() => import('./countries/Ua'));
const UG = lazy(() => import('./countries/Ug'));
const UM = lazy(() => import('./countries/Um'));
const US = lazy(() => import('./countries/Us'));
const UY = lazy(() => import('./countries/Uy'));
const UZ = lazy(() => import('./countries/Uz'));
const VA = lazy(() => import('./countries/Va'));
const VC = lazy(() => import('./countries/Vc'));
const VE = lazy(() => import('./countries/Ve'));
const VG = lazy(() => import('./countries/Vg'));
const VI = lazy(() => import('./countries/Vi'));
const VN = lazy(() => import('./countries/Vn'));
const VU = lazy(() => import('./countries/Vu'));
const WF = lazy(() => import('./countries/Wf'));
const WS = lazy(() => import('./countries/Ws'));
const XK = lazy(() => import('./countries/Xk'));
const YE = lazy(() => import('./countries/Ye'));
const YT = lazy(() => import('./countries/Yt'));
const ZA = lazy(() => import('./countries/Za'));
const ZM = lazy(() => import('./countries/Zm'));
const ZW = lazy(() => import('./countries/Zw'));

export type CountryCode = "AD" | "AE" | "AF" | "AG" | "AI" | "AL" | "AM" | "AO" | "AQ" | "AR" | "AS" | "AT" | "AU" | "AW" | "AX" | "AZ" | "BA" | "BB" | "BD" | "BE" | "BF" | "BG" | "BH" | "BI" | "BJ" | "BL" | "BM" | "BN" | "BO" | "BQ" | "BR" | "BS" | "BT" | "BV" | "BW" | "BY" | "BZ" | "CA" | "CC" | "CD" | "CF" | "CG" | "CH" | "CI" | "CK" | "CL" | "CM" | "CN" | "CO" | "CR" | "CU" | "CV" | "CW" | "CX" | "CY" | "CZ" | "DE" | "DJ" | "DK" | "DM" | "DO" | "DZ" | "EC" | "EE" | "EG" | "EH" | "ER" | "ES" | "ET" | "EU" | "FI" | "FJ" | "FK" | "FM" | "FO" | "FR" | "GA" | "GB" | "ENG" | "NIR" | "SCT" | "WLS" | "GD" | "GE" | "GF" | "GG" | "GH" | "GI" | "GL" | "GM" | "GN" | "GP" | "GQ" | "GR" | "GS" | "GT" | "GU" | "GW" | "GY" | "HK" | "HM" | "HN" | "HR" | "HT" | "HU" | "ID" | "IE" | "IL" | "IM" | "IN" | "IO" | "IQ" | "IR" | "IS" | "IT" | "JE" | "JM" | "JO" | "JP" | "KE" | "KG" | "KH" | "KI" | "KM" | "KN" | "KP" | "KR" | "KW" | "KY" | "KZ" | "LA" | "LB" | "LC" | "LI" | "LK" | "LR" | "LS" | "LT" | "LU" | "LV" | "LY" | "MA" | "MC" | "MD" | "ME" | "MF" | "MG" | "MH" | "MK" | "ML" | "MM" | "MN" | "MO" | "MP" | "MQ" | "MR" | "MS" | "MT" | "MU" | "MV" | "MW" | "MX" | "MY" | "MZ" | "NA" | "NC" | "NE" | "NF" | "NG" | "NI" | "NL" | "NO" | "NP" | "NR" | "NU" | "NZ" | "OM" | "PA" | "PE" | "PF" | "PG" | "PH" | "PK" | "PL" | "PM" | "PN" | "PR" | "PS" | "PT" | "PW" | "PY" | "QA" | "RE" | "RO" | "RS" | "RU" | "RW" | "SA" | "SB" | "SC" | "SD" | "SE" | "SG" | "SH" | "SI" | "SJ" | "SK" | "SL" | "SM" | "SN" | "SO" | "SR" | "SS" | "ST" | "SV" | "SX" | "SY" | "SZ" | "TC" | "TD" | "TF" | "TG" | "TH" | "TJ" | "TK" | "TL" | "TM" | "TN" | "TO" | "TR" | "TT" | "TV" | "TW" | "TZ" | "UA" | "UG" | "UM" | "US" | "UY" | "UZ" | "VA" | "VC" | "VE" | "VG" | "VI" | "VN" | "VU" | "WF" | "WS" | "XK" | "YE" | "YT" | "ZA" | "ZM" | "ZW";
type FlagMaps = {
    [key: string]: React.LazyExoticComponent<(props: React.SVGProps<SVGSVGElement>) => JSX.Element>
}

const flagMaps: FlagMaps = {
    AD, AE, AF, AG, AI, AL, AM, AO, AQ, AR, AS, AT, AU, AW, AX, AZ, BA, BB, BD, BE, BF, BG, BH, BI, BJ, BL, BM, BN, BO, BQ, BR, BS, BT, BV, BW, BY, BZ, CA, CC, CD, CF, CG, CH, CI, CK, CL, CM, CN, CO, CR, CU, CV, CW, CX, CY, CZ, DE, DJ, DK, DM, DO, DZ, EC, EE, EG, EH, ER, ES, ET, EU, FI, FJ, FK, FM, FO, FR, GA, GB, ENG, NIR, SCT, WLS, GD, GE, GF, GG, GH, GI, GL, GM, GN, GP, GQ, GR, GS, GT, GU, GW, GY, HK, HM, HN, HR, HT, HU, ID, IE, IL, IM, IN, IO, IQ, IR, IS, IT, JE, JM, JO, JP, KE, KG, KH, KI, KM, KN, KP, KR, KW, KY, KZ, LA, LB, LC, LI, LK, LR, LS, LT, LU, LV, LY, MA, MC, MD, ME, MF, MG, MH, MK, ML, MM, MN, MO, MP, MQ, MR, MS, MT, MU, MV, MW, MX, MY, MZ, NA, NC, NE, NF, NG, NI, NL, NO, NP, NR, NU, NZ, OM, PA, PE, PF, PG, PH, PK, PL, PM, PN, PR, PS, PT, PW, PY, QA, RE, RO, RS, RU, RW, SA, SB, SC, SD, SE, SG, SH, SI, SJ, SK, SL, SM, SN, SO, SR, SS, ST, SV, SX, SY, SZ, TC, TD, TF, TG, TH, TJ, TK, TL, TM, TN, TO, TR, TT, TV, TW, TZ, UA, UG, UM, US, UY, UZ, VA, VC, VE, VG, VI, VN, VU, WF, WS, XK, YE, YT, ZA, ZM, ZW
}

type Props = {
    countryCode: CountryCode | undefined,
    suspenseFallback?: React.ReactNode
    className?: string,
}

const CountryFlag = (props: Props) => {
    const CountryFlagComponent = props.countryCode ? flagMaps[props.countryCode] || React.Fragment : React.Fragment;
    return (
        <Suspense fallback={props.suspenseFallback || <></>}>
            <div className={props.className}>
                <CountryFlagComponent />
            </div>
        </Suspense>
    )
}
export default CountryFlag
